# DATA TYPES :

Numpy Supports a greater Variety of Data Types in Comparison to Python

Here is a list of all the Primitve Data Types offered in Numpy :

1. np.bool . . . . . . . . . . . . . . . . . (Boolean)

2. np.byte . . . . . . . . . . . . . . . . . (Signed Char)
3. np.ubyte . . . . . . . . . . . . . . . . (Unsigned Char)

4. np.short	. . . . . . . . . . . . . . . . .(Short Int) 
5. np.ushort . . . . . . . . . . . . . . . .(Unsigned Short Int)
6. np.intc . . . . . . . . . . . . . . . . . . (Integer)
7. np.uintc . . . . . . . . . . . . . . . . .(Unsigned Integer)
8. np.int_ . . . . . . . . . . . . . . . . . . (Long Int)
9. np.uint . . . . . . . . . . . . . . . . . .(Unsigned Long Int)
10. np.longlong . . . . . . . . . . . . . (Long Long Int)
11. np.ulonglong . . . . . . . . . . . . (Unsigned Long Long Int)

12. np.half [or] np.float16 . . . . .(Half Precision Float)
13. np.single . . . . . . . . . . . . . . . . (Float)
14. np.double . . . . . . . . . . . . . . . (Double Float)
15. np.longdouble . . . . . . . . . . . (Long Double)

16. np.csingle . . . . . . . . . . . . . . . (Float Complex)
17. np.cdouble . . . . . . . . . . . . . . (Double Complex)
18. np.clongdouble . . . . . . . . . . (Long Double Complex)

Numpy also offers certain Aliases for Fixed Size Data Types : 

1. np.int8 . . . . . . . . . . . . . . . . . .(8 Bit Integer)
2. np.int16 . . . . . . . . . . . . . . . . .(16 Bit Integer)
3. np.int32 . . . . . . . . . . . . . . . . .(32 Bit Integer)
4. np.int64	. . . . . . . . . . . . . . . . .(64 Bit Integert) 

5. np.uint8 . . . . . . . . . . . . . . . . (8 Bit Unsigned Integer)
6. np.uint16 . . . . . . . . . . . . . . . (16 Bit Unsigned Integer)
7. np.uint32 . . . . . . . . . . . . . . . (32 Bit Unsigned Integer)
8. np.uint64 . . . . . . . . . . . . . . . (64 Bit Unsigned Integer)

9. np.float32 . . . . . . . . . . . . . . .(Float)
10. np.float64 . . . . . . . . . . . . . . .(Double)
11. np.complex64 . . . . . . . . . . .(64 Bit Complex)
12. np.complex128 . . . . . . . . . .(128 Bit Complex)


Remember to run the command 'pip install numpy' in your VS Code Terminal at the File Location of the project for the numpy import to work.


Importing Numpy module with alias np

In [9]:
import numpy as np

Setting x to 1.0 with Data Type : 32 Bit Float (Float)

In [13]:
x = np.float32(1.0)
print(x)

1.0


Setting x with Data Type : 64 Bit Float (Double)

In [14]:
x = np.float64(946464646464646464646464646464466.333131313113)
print(x)

9.464646464646464e+32


Setting x with a Array of values of Data Type : Long Int

In [15]:
x = np.int_([1,2,4])
print(x)

[1 2 4]


The np.arange() function :

<div> 
Creates an Array of values, given a Range and a Step Value.
</div>

Syntax : np.arange(start, stop, step)


1. Start = Starting value of the range
2. Stop = Ending value of the range
3. Step = The amount by which each value is skipped




In [16]:
x = np.arange(3, dtype=np.uint8)
print(x)

[0 1 2]


<div>
Additionally, one can set the data type of the array also.
</div>
Syntax : np.arange(start, stop, step, d_type=' ')

In [24]:
x = np.array([1, 2, 3], dtype='f')
print(x)

[1. 2. 3.]


Note that how the output is an Array Type. 

1. When just invoked, it shows the value of x as an Array.
2. When passed as a parameter to print(), it prints the elements of the Array.

In [23]:
x = np.arange(2, 10, 2)
x

array([2, 4, 6, 8])

In [22]:
x = np.arange(2, 10, 2)
print(x)

[2 4 6 8]
