There are 5 general mechanisms for creating arrays:

1. Conversion from other Python structures (e.g., lists, tuples)
2. Intrinsic numpy array creation objects (e.g., arange, ones, zeros, etc.)
3. Reading arrays from disk, either from standard or custom formats
4. Creating arrays from raw bytes through the use of strings or buffers
5. Use of special library functions (e.g., random)

In [2]:
import numpy as np

The np.zeros((m, n, p, . . . , q)) Function.

<div>
Creates an (m) x (n) x (p) x .... x (q) dimensional with every index set to 0.0 (0 as a Float Data Type)
</div>

In [4]:
np.zeros((2, 3, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

The np.ones((m, n, p, . . . , q)) Function.

<div>
Creates an (m) x (n) x (p) x .... x (q) dimensional with every index set to 1.0 (0 as a Float Data Type)
</div>

In [5]:
np.ones((5, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

A few more Intrinsic Array Creation Methods :

np.array() : This will convert any given Python list into a Numpy Array

In [18]:
x = np.array([1, 2, 3])
print(x)

[1 2 3]


In [19]:
x = np.array([[0, 0],[1, 1]])
print(x)

[[0 0]
 [1 1]]


np.arange(start, stop, step) : Start of Range, Stop of Range, Step value by which each value is incremented

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(3.5, 9.8, 0.2)

array([3.5, 3.7, 3.9, 4.1, 4.3, 4.5, 4.7, 4.9, 5.1, 5.3, 5.5, 5.7, 5.9,
       6.1, 6.3, 6.5, 6.7, 6.9, 7.1, 7.3, 7.5, 7.7, 7.9, 8.1, 8.3, 8.5,
       8.7, 8.9, 9.1, 9.3, 9.5, 9.7])

In [9]:
np.arange(2, 10, dtype=float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [10]:
np.arange(2, 10, 0.2)

array([2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4,
       4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. ,
       7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6,
       9.8])

np.linspace(start, stop, number_of_elements) : Start of Range, Stop of Range, Total Number of Elements between the Range (Automatically calculated by numpy)

In [11]:
np.linspace(5, 10, 6)

array([ 5.,  6.,  7.,  8.,  9., 10.])

In [12]:
np.linspace(1, 10, 20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

The np.indices() Function :

This function is useful as it is able to give the entire array in the form of different indexes. The following examples will make it easier to understand :

Syntax : np.indices((shape_of_array))



Creates an array containing all indexes => 

For a 2x2 matrix :\
00 01\
10 11

<div>
The index i is = (0,0),(1,1)\
The index j is = (0,1),(0,1)
</div>

In [14]:
np.indices((2, 2))

array([[[0, 0],
        [1, 1]],

       [[0, 1],
        [0, 1]]])

Also Note : We can use this information to create new arrays with certain expressions of i and j

In [17]:
i, j = np.indices((2,3))
M = 2*i + 3*j

print(M)
#Note how it is printing each value of M in 2*i + 3*j

[[0 3 6]
 [2 5 8]]
