# ARRAY INDEXING :

Array indexing refers to any use of the square brackets ([]) to index array values. Numpy has many powerful options for Indexing.

In [1]:
import numpy as np

# Single Element Indexing : 

In [2]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
print(x[5])

5


# SHAPE() :

arr.shape() - Reshapes the given Array 'arr' into required dimensions.

In [6]:
# let's create an array
x = np.arange(10)
print("1D :",x)

# let's make the array 2 dimensional
x.shape = (2, 5)
print("2D :",x)

1D : [0 1 2 3 4 5 6 7 8 9]
2D : [[0 1 2 3 4]
 [5 6 7 8 9]]


Notice how we do not have to index it using multiple Square Brackets like in Python. We can simply give the location as an Array Itself.

For eg:\
arr[m][n] is equivalent to arr[m, n] in numpy 

Some other Indexing Options :


In [7]:
# let's try to access array elements
print(x[1, 2]) #7
print(x[0, 2])  #2
print(x[1, 3])  #8

7
2
8


In [11]:
# The regular method of indexing also works
print(x[1][2]) #7
print(x[0][2])  #2
print(x[1][3])  #8

7
2
8


In [10]:
# let's try to get the rows of the array

print(x[0])
print(x[1])

[0 1 2 3 4]
[5 6 7 8 9]


# Array Slicing :

In [12]:
# slicing

x = np.arange(20)
print(x[5:11]) #5 6 7 8 9 10 

[ 5  6  7  8  9 10]


In [13]:
x = [1, 2, 3, 4, 5]
x= x[::-1]
x

[5, 4, 3, 2, 1]

In [14]:
x = np.array([1, 2, 3, 4, 5])
print(x[:-3])
print(x[:3])
print(x[-3:])
print(x[3:])

[1 2]
[1 2 3]
[3 4 5]
[4 5]


Along with Slicing, even conditional slicing works :

In [15]:
x = np.array([2, -4, 5, -6, 7, 0])
x = x[x > 0]
x

array([2, 5, 7])

In [16]:
# indexing through values

print(x[x > 2])
print(x[x == 3])
print(x[x >= 2])

[5 7]
[]
[2 5 7]


Here are some code snippets to show the power of numpy :

In [17]:
#To print squares of a given array
x = [1, 2, 3, 4, 5]
z = (a**2 for a in x)

q = []
for i in z:
    q.append(i)
print(q)

[1, 4, 9, 16, 25]


In [18]:
#divides each element by 3
x = [1, 2, 3, 4, 5]
z = [a/3 for a in x]
z

[0.3333333333333333,
 0.6666666666666666,
 1.0,
 1.3333333333333333,
 1.6666666666666667]