# NUMPY FUNCTIONS :

To read about the documentation of any known Numpy function, simply use the help() function. 

In [2]:
import numpy as np

#giving the documentation of array() function
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', '

# RANDOM()

np.random.random() : Creates an Array of required shape with elements with value between 0 and 1

In [3]:
np.random.random(3)

array([0.51391812, 0.96498063, 0.57751336])

In [4]:
np.random.random(11)

array([0.51494381, 0.6073089 , 0.24880899, 0.26980637, 0.09226738,
       0.8703373 , 0.84271142, 0.09255375, 0.25725112, 0.69325718,
       0.3104078 ])

# FULL() :

np.full((shape), element) : Creates an Array of given shape with value given in Parameter.

In [5]:
np.full((2,5), 6)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [6]:
np.full(5, 9)

array([9, 9, 9, 9, 9])

# TILE() : 

np.tile((shape), n) : Creates an array of a given Pattern n times.

In [7]:
np.tile([0, 1], 5)

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [8]:
np.tile([0, 1], [3, 4])

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

# EYE() : 

np.eye(size) : Creates an Identity Matrix of required size. [Square]

In [9]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [10]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

np.random.randInt(Start, Stop) : Creates a Random Array of Integers within given range.

In [11]:
np.random.randint(1, 100)

34

In [12]:
#Default Start = 0
np.random.randint(30)

8

In [13]:
np.random.randint(-40, 40)

34

# ELEMENT INSPECTION : 

Functions to INSPECT the contents of Numpy Arrays :

1. shape() : Shape of array (m x n)
2. dtype() : Data type (int, float etc.)
3. ndim() :  Number of dimensions (or axes)
4. itemsize() : Memory used by each array elememnt in bytes

In [14]:
#for example :
a = np.array([2, 3, 45, 6])
print(a)

[ 2  3 45  6]


In [15]:
a.shape

(4,)

In [16]:
a.dtype

dtype('int32')

In [17]:
a.ndim

1

In [18]:
a.itemsize

4