# NUMPY OPERATIONS :

Operations on Numpy Arrays :

1. Manipulating Arrays
2. Mathematical Operations on Arrays

Manipulating Arrays :

1. Reshaping Arrays
2. Transposing Arrays
3. Stacking Arrays

In [1]:
import numpy as np

# Reshaping Arrays : 

Reshaping is done using the reshape() function.

In [2]:
# lets take an array a and take 12 elements inside it

a = np.arange(0, 12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [3]:
# lets try to resize this array

print('Array with 3 Rows and 4 Columns')
b = a.reshape(3, 4)
print(b,'\n')

print('Array with 4 Rows and 3 Columns')
c = a.reshape(4, 3)
print(c, '\n')

print('Array with 6 Rows and 2 Columns')
d = a.reshape(6, 2)
print(d, '\n')

print('Array with 2 Rows and 6 Columns')
e = a.reshape(2, 6)
print(e, '\n')

Array with 3 Rows and 4 Columns
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

Array with 4 Rows and 3 Columns
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 

Array with 6 Rows and 2 Columns
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]] 

Array with 2 Rows and 6 Columns
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]] 



Note : Dimension of -1 automatically resizes it to whatever is needed.

In [4]:
# If you specify -1 as a dimension, the dimensions are automatically calculated

x = a.reshape(4, -1)
y = a.reshape(3, -1)
z = a.reshape(6, -1)
q = a.reshape(2, -1)

print(x, '\n')
print(y, '\n')
print(z, '\n')
print(a, '\n')

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]] 

[ 0  1  2  3  4  5  6  7  8  9 10 11] 



# Transposing Arrays : 

This is done using x.T

In [5]:
# lets make an array and transpose the array

# lets take an array
array = np.array([[3, 4, 4],[7, 7,8]])

print('Before Transposition of Array b')
print(array)

# lets transpose the array
transpose = array.T

print('After Transposition of Array a')
print(transpose)

Before Transposition of Array b
[[3 4 4]
 [7 7 8]]
After Transposition of Array a
[[3 7]
 [4 7]
 [4 8]]


# Stacking Arrays : 
Stacking is done using the np.hstack() and np.vstack() methods.

 For horizontal stacking, the number of rows should be the same.\
 For vertical stacking, the number of columns should be the same.

In [9]:
# lets create two arrays for performing the operation of vertical stacking

# for vertical stacking the number of columns must be same
arr1 = np.arange(25).reshape(5, 5)
arr2 = np.arange(25).reshape(5, 5)

print('First Array')
print(arr1, '\n')
print('Second Array')
print(arr2)

First Array
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

Second Array
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


# vstack()

In [10]:
# Note that np.vstack(a, b) throws an error - you need to pass the arrays as a list

np.vstack((arr1, arr2))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# hstack()

In [11]:
# Note that np.hstack(a, b) throws an error - you need to pass the arrays as a list

np.hstack((arr1, arr2))

array([[ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 20, 21, 22, 23, 24]])

# Basic Mathematical Operations : 

1. Single Array Operations
2. Double Array Operations

# Single Array Operations

In [12]:
a = np.array([2, 3, 5, 6, 7, 8])

sin = np.sin(a)
cos = np.cos(a)
tan = np.tan(a)
log = np.log(a)
exp = np.exp(a)
sqrt = np.sqrt(a)
sqrt

array([1.41421356, 1.73205081, 2.23606798, 2.44948974, 2.64575131,
       2.82842712])

In [13]:
x = [2, 3, 4, 5, 6]
z = [1/a for a in x]
z

[0.5, 0.3333333333333333, 0.25, 0.2, 0.16666666666666666]

In [14]:
# lets create an array, where we will perform our operations

array = np.arange(10)

# sin function
print('sin of array a')
sin = np.sin(array)
print(sin, '\n')

# cos function
print('cos of array a')
cos = np.cos(array)
print(cos, '\n')

# tan function
print('tan of array a')
tan = np.tan(array)
print(tan, '\n')

# log function
print('log of array a')
log = np.log(array)
print(log, '\n')

# exp function
print('exp of array a')
exp = np.exp(array)
print(exp, '\n')

# sqrt function
print('sqrt of array a')
exp = np.sqrt(array)
print(exp, '\n')

sin of array a
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849] 

cos of array a
[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219
  0.96017029  0.75390225 -0.14550003 -0.91113026] 

tan of array a
[ 0.          1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501
 -0.29100619  0.87144798 -6.79971146 -0.45231566] 

log of array a
[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458] 

exp of array a
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03] 

sqrt of array a
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ] 



C:\Users\Hitesh\AppData\Local\Temp\ipykernel_6512\1420204510.py:22: RuntimeWarning: divide by zero encountered in log
  log = np.log(array)


# Double Array Operations

In [15]:
# lets take two arrays on which we will perform the operations

a = np.array([7, 5, 2, 3])
b = np.array([5, 8, 3, 5])

# mathematical operations

print('Sum Operation between arrays a and b')
add = np.add(a, b)
print(add, '\n')

print('Subtract Operation between arrays a and b')
subtract = np.subtract(a, b)
print(subtract, '\n')

print('Multiply Operation between arrays a and b')
multiply = np.multiply(a, b)
print(multiply, '\n')

print('Divide Operation between arrays a and b')
div = np.divide(a, b)
print(div, '\n')

print('power Operation between arrays a and b')
power = np.power(a, b)
print(power, '\n')

print('Remainder Operation between arrays a and b')
rem = np.remainder(a, b)
print(rem, '\n')

print('Modulus Operation between arrays a and b')
mod = np.mod(a, b)
print(mod, '\n')

Sum Operation between arrays a and b
[12 13  5  8] 

Subtract Operation between arrays a and b
[ 2 -3 -1 -2] 

Multiply Operation between arrays a and b
[35 40  6 15] 

Divide Operation between arrays a and b
[1.4        0.625      0.66666667 0.6       ] 

power Operation between arrays a and b
[ 16807 390625      8    243] 

Remainder Operation between arrays a and b
[2 5 2 3] 

Modulus Operation between arrays a and b
[2 5 2 3] 

